name: Lighthouse CI

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened, synchronize, labeled]
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'
      - 'package.json'
      - '.lhci/**'

env:
  DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: 📦 Setup dependencies with cache
        uses: victory-sokolov/github-actions/.github/actions/node-deps-cache@main
        with:
          package-manager: bun

      - name: 🏗️ Build project
        run: bun run build

      - name: 🚀 Run Lighthouse CI
        run: bunx lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
